### ISSUE TITLE
Weird menu in mobile layout

### ISSUE THREAD

**Issue by imbrn** [maxwelfcoelho/todo#16]
It's not really a problem, but there's a really weird menu that doesn't' do anything in the mobile layout:

![image](https://user-images.githubusercontent.com/1906977/68086719-79aee800-fe2d-11e9-9ce6-e2adc8425404.png)

I think it's something from the Bootstrap framework (that I really don't like). But as I said, it's not a problem, just something that's weird for me. Not a priority. :)

**Comment by maxwelfcoelho** [comment]
![menu](https://user-images.githubusercontent.com/37268477/68129205-ea223b80-fef7-11e9-8698-69bdfcaec0ae.png)
