### ISSUE TITLE
Bug: Pressing Enter is not working

### ISSUE THREAD

**Issue by imbrn** [maxwelfcoelho/todo#27]
The pressing Enter behavior used to create a Todo Item is not working anymore. 😞 

> I don't know why, but it was working properly before the last updates.

**Comment by maxwelfcoelho** [comment]
Yeah, I changed to alt + enter for a while, I was using one input to edit and add new todos, so when I pressed enter to edit a todo it would add a new todo as well. I will follow your advice and create a edit input for each input and fix this problem. Thank you!

**Comment by maxwelfcoelho** [comment]
It's already working. Thank you!

https://github.com/maxwelfcoelho/todo/commit/194dabf470c56b727c519471c26939cd6359d484
